##spring.application.name=contact-form
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000


server:
  port: 8081

admin:
  default:
    email: admin@msc.com
    password: Admin2025@
